### ISSUE TITLE
Document that it works with `django.contrib.postgres`

### ISSUE THREAD

**Issue by pydanny** [kevinmickey/django-prettyjson#1]

**Comment by axsapronov** [comment]
+1.
Yes, I wanted ask this question :)

**Comment by kevinmickey** [comment]
I tried it out with a jsonfield in a postgres database, and it seems to work fine.  Let me know if you encounter problems though.

I haven't written any tests yet, but feel free to add one -- I'm not sure how to handle tests for different backends.
