### ISSUE TITLE
Parsed widget size

### ISSUE THREAD

**Issue by fcurella** [kevinmickey/django-prettyjson#11]
When loading the widget as initially parsed in the admin, it takes the width and height of the original textarea, making it often too small. The parsed view takes considerably more space, and will often result in unnecessary scrolling:

![screen shot 2017-08-30 at 10 52 38 am](https://user-images.githubusercontent.com/89607/29882147-cce9d8d8-8d71-11e7-88e0-be9c6afe7b67.png)

This is easily fixable in the js, and I've got a fix ready. But I was wondering if you were set on the current behavior, of it there was a specific reason for how it currently works.

**Comment by kevinmickey** [comment]
I guess I try to leave default styling where I can, but I agree that it's usually too small.  It would be awesome if you put your fix into a pull request!
