### ISSUE TITLE
Script run order problem

### ISSUE THREAD

**Issue by feus4177** [kevinmickey/django-prettyjson#13]
I'm using django-prettyjson with Django 2.0 and there seems to be a problem with the order in which the scripts are running. The prettyjson.js file is getting run before the Django jQuery gets loaded and so it throws an error. I was able to fix it with the following snippet:
```python
class FixedPrettyJSONWidget(PrettyJSONWidget):
    class Media:
        js = ('admin/js/jquery.init.js', 'prettyjson/prettyjson.js', )
        css = {
            'all': ('prettyjson/prettyjson.css', )
        }
```
I'm not sure if there is a better way to do it, but hopefully this illustrates the problem.

**Comment by devlounge** [comment]
Thanks, this solved the issue indeed

**Comment by kevinmickey** [comment]
Seems like other widgets are having this issue: https://github.com/django/django/pull/9743
