### ISSUE TITLE
*Quick* Parsed JSON in Template

### ISSUE THREAD

**Issue by Ademord** [kevinmickey/django-prettyjson#16]
I can't seem to figure out how to do 
`
{% load prettyjson %}
{% prettyjson_setup %}
<p>
   {% prettyjson mydict %}
</p>
`
and just show the json already pretty-fied/rendered ? 

Help pls!

**Comment by kevinmickey** [comment]
Thanks for your feedback -- you can now use:

`{% prettyjson mydict initial='parsed' %}`

Fix is now in v0.4.0

**Comment by Ademord** [comment]
Thanks you're awesome!
