### ISSUE TITLE
Django 2.1 stopped supporting widgets without explicit renderer arg definition

### ISSUE THREAD

**Issue by MarianoFontana** [kevinmickey/django-prettyjson#19]
As we can see in the release notes for Django 2.1 (https://docs.djangoproject.com/en/2.1/releases/2.1/):
> Support for Widget.render() methods without the renderer argument is removed.

As this project does not have a `renderer` kwarg, it fails when rendering:
```python
def render(self, name, value, attrs=None):
```

It should be enough to just add:

```python
def render(self, name, value, attrs=None, **kwargs):
```

**Comment by kevinmickey** [comment]
Thanks for the report! Should be fixed in version 0.4.1.
